# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f59d36b26bc96bf8da6c1057d0fcdf36a67c454aee7b3fbbcb9871a01764876639b83ee8c3e2b70e60375bba677040800497b68f344e4ecc8b67a4186ac1e96

test:
  secret_key_base: d551ee4a371743ea18a4875c095c34b3d6e26e1353449c182ea236606b428f39791b0cc77396fee4426806aadf0ed24cf04c78831709daae1af58ed390e87f30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
